name: Screenshot-Action
on:
  push:
    branches:
      - main

jobs:
  copy_repository_then_screenshot:
    runs-on: ubntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: swinton/screenshot-website@v1.0.2
        with:
          source: file:///src/index.html
          destination: screenshot.png
          
